from fpdf import FPDF
import datetime
import re

class PDFExporter(FPDF):
    def header(self):
        # Only add header for regular lessons, not certificates
        if hasattr(self, 'is_certificate') and self.is_certificate:
            return
        # Top Header Bar
        self.set_fill_color(30, 27, 75) # Deep Indigo
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_y(10)
        self.set_font('helvetica', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, 'RamXplain', 0, 1, 'C')
        
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 5, 'Personalized AI Mastery & Insights', 0, 1, 'C')
        self.ln(20)

    def footer(self):
        if hasattr(self, 'is_certificate') and self.is_certificate:
            return
        self.set_y(-20)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.set_draw_color(168, 85, 247)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by RamXplain AI | {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_concept_pdf(concept, explanation, mode="Neutral"):
    pdf = PDFExporter()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()
    
    # Concept Header Section
    pdf.set_fill_color(243, 244, 246) # Light Gray
    pdf.rect(10, 45, 190, 20, 'F')
    
    pdf.set_xy(10, 47)
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(168, 85, 247) # Purple
    pdf.cell(0, 10, f"Topic: {concept}", 0, 1, 'L')
    
    pdf.set_font('helvetica', 'I', 10)
    pdf.set_text_color(107, 114, 128) # Muted gray
    pdf.set_xy(10, 55)
    pdf.cell(0, 10, f"Learning Mode: {mode}", 0, 1, 'L')
    
    pdf.ln(12)
    
    # Content Processing - Simplified Markdown Renderer
    pdf.set_font('helvetica', '', 11)
    pdf.set_text_color(31, 41, 55) # Dark gray text
    
    def sanitize_text(text):
        """Replaces problematic unicode characters with PDF-safe equivalents."""
        replacements = {
            '’': "'", '‘': "'", '”': '"', '“': '"', '—': '-', '–': '-',
            '…': '...', '•': '*', '·': '*', '°': ' deg',
            '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
            '\u201c': '"', '\u201d': '"', '\u2026': '...', '\u2022': '*'
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        # Final safety: encode to latin-1 and back, replacing errors with '?'
        return text.encode('latin-1', 'replace').decode('latin-1')

    lines = explanation.split('\n')
    for line in lines:
        line = sanitize_text(line.strip())
        if not line:
            pdf.ln(5)
            continue
            
        # Heading 3: ### Title
        if line.startswith('###'):
            pdf.ln(3)
            pdf.set_font('helvetica', 'B', 13)
            pdf.set_text_color(124, 58, 237) # Darker purple
            text = line.replace('###', '').strip()
            pdf.multi_cell(0, 8, text)
            pdf.set_font('helvetica', '', 11)
            pdf.set_text_color(31, 41, 55)
            pdf.ln(2)
            
        # Bold Text handling **text**
        elif '**' in line:
            # Simple bold parts: we split by ** and alternate fonts
            # For multi_cell, we have to stay in one font but we can bold the whole line
            # if it's mostly bold, or just keep it regular for better flow in FPDF (without complex HTML)
            # FPDF2 doesn't easily do mixed bold in one multi_cell without Write()
            # Let's use Write for mixed styling
            parts = re.split(r'(\*\*.*?\*\*)', line)
            for part in parts:
                if part.startswith('**') and part.endswith('**'):
                    pdf.set_font('helvetica', 'B', 11)
                    pdf.write(6, part.replace('**', ''))
                else:
                    pdf.set_font('helvetica', '', 11)
                    pdf.write(6, part)
            pdf.ln(7)
            
        # Bullet Points
        elif line.startswith('•') or line.startswith('*') or line.startswith('- '):
            pdf.set_x(15)
            pdf.set_font('helvetica', '', 11)
            text = "* " + line.lstrip('•*- ').strip()
            pdf.multi_cell(0, 6, text)
            
        # Normal Paragraph
        else:
            pdf.set_font('helvetica', '', 11)
            pdf.multi_cell(0, 6, line)
            pdf.ln(2)

    return bytes(pdf.output())

def generate_certificate_pdf(user_name, topic):
    pdf = PDFExporter(orientation='L', unit='mm', format='A4')
    pdf.is_certificate = True
    pdf.add_page()
    
    # --- Professional Border ---
    pdf.set_draw_color(168, 85, 247) # Purple
    pdf.set_line_width(2)
    pdf.rect(5, 5, 287, 200) # Outer
    pdf.set_draw_color(251, 191, 36) # Gold
    pdf.set_line_width(1)
    pdf.rect(8, 8, 281, 194) # Inner
    
    # --- Content ---
    pdf.set_y(30)
    pdf.set_font('helvetica', 'B', 40)
    pdf.set_text_color(30, 27, 75)
    pdf.cell(0, 20, 'CERTIFICATE', 0, 1, 'C')
    
    pdf.set_font('helvetica', 'B', 20)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(0, 10, 'OF CONCEPT MASTERY', 0, 1, 'C')
    
    pdf.ln(15)
    pdf.set_font('helvetica', '', 16)
    pdf.set_text_color(31, 41, 55)
    pdf.cell(0, 10, 'This is proudly presented to', 0, 1, 'C')
    
    pdf.ln(5)
    pdf.set_font('helvetica', 'B', 32)
    pdf.set_text_color(168, 85, 247)
    pdf.cell(0, 20, f"{user_name.upper()}", 0, 1, 'C')
    
    pdf.ln(5)
    pdf.set_font('helvetica', '', 16)
    pdf.set_text_color(31, 41, 55)
    pdf.cell(0, 10, 'for successfully completing the advanced level mastery of', 0, 1, 'C')
    
    pdf.ln(5)
    pdf.set_font('helvetica', 'B', 24)
    pdf.set_text_color(30, 27, 75)
    pdf.cell(0, 15, f"{topic}", 0, 1, 'C')
    
    pdf.ln(20)
    
    # --- Signatures ---
    pdf.set_y(160)
    
    # Left: RamXplain Seal
    pdf.set_x(40)
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(168, 85, 247)
    pdf.cell(60, 10, 'RamXplain AI', 0, 0, 'C')
    
    # Right: Lakshmi Signature
    pdf.set_x(190)
    pdf.set_font('times', 'I', 20)
    pdf.set_text_color(30, 27, 75)
    pdf.cell(60, 10, 'L. Moksha Boya', 0, 1, 'C')
    
    # Lines
    pdf.set_draw_color(156, 163, 175)
    pdf.line(40, 170, 100, 170)
    pdf.line(190, 170, 250, 170)
    
    pdf.set_y(172)
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(107, 114, 128)
    pdf.set_x(40)
    pdf.cell(60, 5, 'Official Platform Seal', 0, 0, 'C')
    pdf.set_x(190)
    pdf.cell(60, 5, 'Issued by: Lakshmi Moksha Boya', 0, 1, 'C')
    
    # --- Date ---
    pdf.set_y(185)
    pdf.set_font('helvetica', 'I', 9)
    pdf.cell(0, 10, f"Certificate ID: RX-{datetime.datetime.now().strftime('%Y%m%d%H%M')} | Date: {datetime.datetime.now().strftime('%B %d, %Y')}", 0, 0, 'C')

    return bytes(pdf.output())
